NIAD-1021: Translate Observation.interpretation additional unit tests
nhsconnect/integration-adaptor-gp2gp pull request #141
Opened 2021-04-06 15:41 UTC by ElliotB-96

* Implemented additional unit tests for more interpretation codes.

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapperTest.java
> +        System.out.println(outputMessage);
Can this be removed?

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/resources/ehr/mapper/observation/example-observation-resource-21.json
> +        "display": "Very High Value"
Can you update this to reflect the test scenario?

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/resources/ehr/mapper/observation/example-observation-resource-19.json
> +        "display": "Very High Value"
Can you also update this to reflect the test scenario?

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/resources/ehr/mapper/observation/example-observation-resource-20.json
> +        "display": "Very High Value"
And this one too

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/resources/ehr/mapper/observation/example-observation-resource-23.json
> +        "display": "Very High Value"
Can you update this to reflect the test scenario?

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/resources/ehr/mapper/observation/example-observation-resource-22.json
> +        "display": "Very High Value"
And this one too

2021-04-07 08:32 UTC, n-r-b commented on service/src/test/resources/ehr/mapper/observation/expected-output-observation-statement-16.xml
> +                <text>Range: Text: Test reference range text High: 20 Test comment</text>
Should this mention "High" when the interpretation code is low (that's if this is related)? I'm not too familiar with the logic behind this

2021-04-08 08:56 UTC, mattd-kainos requested changes
@ElliotB-96  to double check that all four conditions described by the mapping spreadsheet have been covered

2021-04-08 09:11 UTC, mattd-kainos submitted a review, later dismissed
@ElliotB-96 provided evidence interpretation text is covered

2021-04-08 09:35 UTC, n-r-b submitted a review, later dismissed

2021-04-08 13:50 UTC, Broom94 submitted a review, later dismissed

2021-04-09 08:10 UTC, n-r-b commented on service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapperTest.java
> +        System.out.println(outputMessage);
It's re-appeared again!

2021-04-09 08:13 UTC, n-r-b approved these changes

2021-04-09 09:17 UTC, mattd-kainos approved these changes

2021-04-09 09:18 UTC, merged