NIAD-1096 Encounter participant to EhrComposition author
nhsconnect/integration-adaptor-gp2gp pull request #156
Opened 2021-04-14 10:15 UTC by andrewwa-kainos

https://gpitbjss.atlassian.net/browse/NIAD-1317

AC9 - add author element to ehrComposition

GIVEN Encounter is translated to ehrComposition
AND Encounter.participant of type “REC” is translated to Agent
THEN author element is added to ehrComposition
AND author/agentRef is referencing Agent
AND author.time value is taken from List.time field from consultation list referencing the encounter

2021-04-14 10:15 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ParticipantCoding.java
> +    RECORDER("REC");
This enum will be extended for AC10

2021-04-14 10:16 UTC, andrewwa-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/EncounterExtractor.java
> +    private static final String ENCOUNTER_LIST_CODE = "1149501000000101";
Just a clarification requested by @mattd-kainos - otherwise doesn't impact this PR.

2021-04-14 10:17 UTC, andrewwa-kainos commented on service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapperTest.java
> +            .setDate(CONSULTATION_DATE));
Anyone have a nicer way to set up this data?

2021-04-14 16:37 UTC, mattd-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java
> +            .map(Date::toInstant)
Need to review this conversion of Date to Instant. HAPI does some very strange things with Date and this may represent the system's local time zone

2021-04-14 16:42 UTC, mattd-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java
> +            .map(Date::toInstant)
yes, I think you'll need to use the `public static String toHl7Format(BaseDateTimeType baseDateTimeType)` version of this method instead.

2021-04-14 16:44 UTC, mattd-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterMapper.java
> +        recReference.ifPresent(encounterStatementTemplateParameters::author);
> Exception - if there is no participant of type code REC then log the issue and stop process it's a MUST as far as GPC spec is concerned

Not optional, we need to throw an error if we don't find the RECORDER participant.

2021-04-14 16:47 UTC, mattd-kainos requested changes
Looks good, just need to address the HL7 date/time conversion and mandatory author/recorder.

2021-04-15 13:14 UTC, mattd-kainos approved these changes

2021-04-19 09:33 UTC, msolecka approved these changes

2021-04-19 10:07 UTC, merged