NIAD-1270: Disable mapping for ptl test
nhsconnect/integration-adaptor-gp2gp pull request #183
Opened 2021-04-27 14:44 UTC by Broom94

2021-04-27 14:45 UTC, z-uddin approved these changes

2021-04-27 14:46 UTC, ElliotB-96 approved these changes

2021-04-28 08:43 UTC, ElliotB-96 approved these changes

2021-04-28 08:47 UTC, ElliotB-96 approved these changes

2021-04-28 08:55 UTC, ElliotB-96 approved these changes

2021-04-28 09:27 UTC, z-uddin approved these changes

2021-04-28 10:40 UTC, mattd-kainos requested changes
"Request changes" to ensure it doesn't get merged

2021-04-28 13:57 UTC, closed without merging