NIAD-1339 generate uppercase UUIDs
nhsconnect/integration-adaptor-gp2gp pull request #185
Opened 2021-04-28 09:16 UTC by dawidskainos

2021-04-28 09:47 UTC, z-uddin commented on service/src/test/java/uk/nhs/adaptors/gp2gp/common/service/RandomIdGeneratorServiceTest.java
> +            () -> assertThat(id2).matches("[A-Z0-9-]+")
Regex for UUIDs is `[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}`
For uppercase we simply this to use `[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}` to test against?

2021-04-28 09:57 UTC, z-uddin submitted a review, later dismissed

2021-04-28 10:45 UTC, mattd-kainos requested changes
https://github.com/nhsconnect/integration-adaptor-gp2gp/pull/162 adds a stub id generator (service/src/test/java/uk/nhs/adaptors/gp2gp/RandomIdGeneratorServiceStub.java) and list of ids (service/src/test/resources/uuids.txt). It would be nice if we merge 162 before this PR and then uppercase these for the UAT output in this PR.

2021-04-29 06:54 UTC, mattd-kainos submitted a review, later dismissed

2021-04-29 07:22 UTC, closed without merging