NIAD-1445: Update changelog
nhsconnect/integration-adaptor-gp2gp pull request #222
Opened 2021-05-12 09:47 UTC by Broom94

2021-05-12 09:54 UTC, mattd-kainos commented on CHANGELOG.md
> +- All vunerabile dependencies fixed with exception to one that current has no fxied list below in known issues.
List the fixed vulnerabilities in the "Fixed" section

2021-05-12 09:56 UTC, andrewwa-kainos requested changes

2021-05-12 09:56 UTC, andrewwa-kainos commented on CHANGELOG.md
> +- Enivronment variables updated in corrisponsing vars files in docker for integration with GPCC 0.0.5 changes. (Update environment variables accordingly)
```suggestion
- Environment variables updated in corresponding vars files in docker for integration with GPCC 0.0.5 changes. (Update environment variables accordingly.)
```

2021-05-12 09:56 UTC, andrewwa-kainos commented on CHANGELOG.md
> +- Known to be a broke version
```suggestion
- Known to be a broken version
```

2021-05-12 10:55 UTC, andrewwa-kainos requested changes

2021-05-12 10:55 UTC, andrewwa-kainos commented on CHANGELOG.md
> +- All vunerabile dependencies fixed with exception to one that current has no fxied list below in known issues.
```suggestion
- All vulnerable dependencies fixed with exception to one that currently has no fix listed below in known issues.
```

2021-05-12 10:55 UTC, andrewwa-kainos commented on CHANGELOG.md
> +- Known to be a broken version due to missing environment variables needed for GPCC inegration.
```suggestion
- Known to be a broken version due to missing environment variables needed for GPCC integration.
```

2021-05-12 11:02 UTC, andrewwa-kainos approved these changes

2021-05-13 07:53 UTC, mattd-kainos approved these changes

2021-05-13 08:20 UTC, merged