NIAD-1530 - MedicationRequest: Place discontinuation reason term text in ehrSupplyDiscontinue/pertinentInformation
nhsconnect/integration-adaptor-gp2gp pull request #297
Opened 2021-08-16 12:33 UTC by bbell-kainos

2021-08-19 14:37 UTC, bartek-sarul requested changes

2021-08-19 14:37 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementExtractor.java
> +        return statusReason
Inline it

2021-08-19 14:37 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementExtractor.java
> +            .map(value -> value.get())
Can be `.map(<something>::get)`

2021-08-23 15:13 UTC, rorysproule1 approved these changes

2021-08-25 10:51 UTC, dawidskainos approved these changes

2021-08-25 10:52 UTC, merged