NIAD-1171: Handle ProcedureRequest.supportingInfo as Notes/text
nhsconnect/integration-adaptor-gp2gp pull request #299
Opened 2021-08-18 12:58 UTC by AlanSimpson1723

2021-08-19 12:08 UTC, rorysproule1 submitted a review, later dismissed

2021-08-19 14:30 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/DiaryPlanStatementMapper.java
> +        return reference.getReferenceElement().getResourceType().equals(ResourceType.Observation.name());
It's usually better to compare a const with a variable rather than the opposite.

2021-08-19 14:32 UTC, bartek-sarul requested changes

2021-08-19 14:32 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/EncounterComponentsMapper.java
> +            IS_NESTED)
Having this formatted like tells me that `IS_NESTED` is a 2nd parameter of `ofNullable`.
Move it so it's all on line 188

2021-08-20 11:42 UTC, ElliotB-96 approved these changes

2021-08-20 12:06 UTC, bartek-sarul approved these changes

2021-08-20 12:07 UTC, merged