Added mocked gpc to wiremock for ok and not found status
nhsconnect/integration-adaptor-gp2gp pull request #30
Opened 2021-01-07 13:49 UTC by mmackiewicz1

2021-01-07 14:29 UTC, mattd-kainos commented on docker/wiremock/stubs/__files/emptyPatientDocumentResponse.json
> +
This should be a FHIR OperationOutcome response

2021-01-07 15:50 UTC, mattd-kainos commented on docker/wiremock/stubs/__files/emptyPatientDocumentResponse.json
> +{
Filename is `emptyPatientDocumentResponse.json` but response is no longer empty

2021-01-07 16:00 UTC, mattd-kainos commented on docker/wiremock/stubs/__files/emptyPatientDocumentResponse.json
> +  "issue" : [{
This response is very different from the GP Connect API's 404 response

```
{
    "resourceType": "OperationOutcome",
    "meta": {
        "profile": [
            "https://fhir.nhs.uk/StructureDefinition/gpconnect-operationoutcome-1"
        ]
    },
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "details": {
                "coding": [
                    {
                        "system": "https://fhir.nhs.uk/ValueSet/gpconnect-error-or-warning-code-1",
                        "code": "NO_RECORD_FOUND",
                        "display": "No Record Found"
                    }
                ]
            },
            "diagnostics": "No record found"
        }
    ]
}
```

https://orange.testlab.nhs.uk/swagger-v1-5-documents.html

2021-01-07 16:01 UTC, mattd-kainos requested changes
404 response different from GPC API

2021-01-08 10:17 UTC, mattd-kainos approved these changes
Tested with postman - public demonstrator and wiremock side by side. Only difference is response headers but that's not significant or part of the story. Nice work!

2021-01-08 10:19 UTC, Broom94 approved these changes

2021-01-08 10:19 UTC, merged

2021-01-12 10:41 UTC, Broom94 reviewed
The response returned isn't the same as orangetest labs

2021-01-12 10:41 UTC, Broom94 commented on docker/wiremock/stubs/mappings/retreiveNoneExistingPatientDocument.json
> +      "Content-Type": "application/json"
content type should be application/fhir+json

2021-01-12 10:41 UTC, Broom94 commented on docker/wiremock/stubs/mappings/retrievePatientDocument.json
> +      "Content-Type": "application/json"
content type should be application/fhir+json

2021-01-12 10:42 UTC, Broom94 commented
There are some missing headers, below is an orangetestlab response header above are what the mock is returning, i'll send you a screenshot