NIAD-1608: Ignore QuestionnaireResponse resource
nhsconnect/integration-adaptor-gp2gp pull request #312
Opened 2021-09-01 11:14 UTC by rorysproule1

2021-09-02 13:31 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/IgnoredResourcesUtils.java
> +    private static final List<ResourceType> IGNORED_RESOURCES = List.of(
It doesn't matter much in this case BUT "in theory" a `Set` is more suitable for such case.

2021-09-02 13:32 UTC, bartek-sarul submitted a review, later dismissed

2021-09-02 14:31 UTC, bbell-kainos submitted a review, later dismissed

2021-09-03 08:59 UTC, bartek-sarul approved these changes

2021-09-06 14:09 UTC, bartek-sarul requested changes

2021-09-06 14:28 UTC, bbell-kainos approved these changes

2021-09-06 14:49 UTC, rorysproule1 commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NonConsultationResourceMapper.java
> +        if (IgnoredResourcesUtils.isIgnoredResourceType(resource.getResourceType())) {
Implemented

2021-09-07 09:27 UTC, bartek-sarul approved these changes

2021-09-07 10:25 UTC, merged