NIAD-789: mock gpc api structured record
nhsconnect/integration-adaptor-gp2gp pull request #33
Opened 2021-01-11 16:05 UTC by ElliotB-96

Request body used for testing this:

> {
    "resourceType": "Parameters",
    "parameter": [
        {
            "name": "patientNHSNumber",
            "valueIdentifier": {
                "system": "https://fhir.nhs.uk/Id/nhs-number",
                "value": "9690937286"
            }
        }
    ]
}

2021-01-11 16:55 UTC, mattd-kainos commented on docker/wiremock/stubs/mappings/retrieveNonExistingPatientStructureRecord.json
> +    "body": "",
Can we use the OperationOutcome response for 404?

```
{
    "resourceType": "OperationOutcome",
    "meta": {
        "profile": [
            "https://fhir.nhs.uk/STU3/StructureDefinition/GPConnect-OperationOutcome-1"
        ]
    },
    "issue": [
        {
            "severity": "error",
            "code": "not-found",
            "details": {
                "coding": [
                    {
                        "system": "https://fhir.nhs.uk/STU3/CodeSystem/Spine-ErrorOrWarningCode-1",
                        "code": "PATIENT_NOT_FOUND",
                        "display": "PATIENT_NOT_FOUND"
                    }
                ]
            },
            "diagnostics": "No patient details found for patient ID: 9876543210"
        }
    ]
}
```

2021-01-11 16:55 UTC, mattd-kainos requested changes
needs to use operationoutcome response body for not found

2021-01-11 17:15 UTC, mattd-kainos submitted a review, later dismissed

2021-01-12 10:49 UTC, Broom94 submitted a review, later dismissed
There are some missing headers, below is an orangetestlab response header above are what the mock is returning, i'll send you a screenshot

Content returned isn't the same as orange test labs body

2021-01-12 10:49 UTC, Broom94 commented on docker/wiremock/stubs/mappings/retrieveNonExistingPatientStructureRecord.json
> +      "Content-Type": "application/json"
content type should be application/fhir+json

2021-01-12 10:49 UTC, Broom94 commented on docker/wiremock/stubs/mappings/retrievePatientStructuredRecord.json
> +      "Content-Type": "application/json"
content type should be application/fhir+json

2021-01-13 09:00 UTC, mattd-kainos approved these changes
tested with postman, similar replies from public demonstrator and wiremock

2021-01-13 09:06 UTC, z-uddin commented
Have tested with postman, and it looks good.
Responses are similar from the wiremock and the orange.testlab demonstrator.

2021-01-13 09:07 UTC, z-uddin approved these changes

2021-01-13 09:14 UTC, merged