Feature/NIAD-1389 document task queue payloads
nhsconnect/integration-adaptor-gp2gp pull request #348
Opened 2021-09-24 08:10 UTC by ElliotB-96

- Added example task payloads

2021-09-27 07:57 UTC, bartek-sarul requested changes

2021-09-27 07:57 UTC, bartek-sarul commented on documentation/examples/Task queue payloads/GetGpcDocumentTaskDefinition
> +{
Are those examples referenced somewhere in the documentation?

2021-09-27 08:25 UTC, michael-kainos submitted a review, later dismissed

2021-09-28 09:19 UTC, bartek-sarul approved these changes

2021-10-04 08:59 UTC, bbell-kainos approved these changes

2021-10-04 09:17 UTC, merged