NIAD-1592: Immunization: When site is processed into to text the term text is incorrect for synonyms
nhsconnect/integration-adaptor-gp2gp pull request #349
Opened 2021-09-24 10:02 UTC by bbell-kainos

2021-09-27 13:18 UTC, bartek-sarul requested changes

2021-09-27 13:18 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/CodeableConceptMappingUtils.java
> +            .filter(extension -> extension.getUrl().equals(DISPLAY_EXTENSION_URL))
Always compare const to a variable.
```
DISPLAY_EXTENSION_URL.equals(extension.getUrl())
```

2021-09-27 13:18 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/CodeableConceptMappingUtils.java
> +            .filter(extension -> extension.getUrl().equals(DESCRIPTION_DISPLAY_URL))
The same comment as above

2021-09-27 14:26 UTC, rorysproule1 approved these changes

2021-09-28 09:59 UTC, bbell-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/CodeableConceptMappingUtils.java
> +            .filter(extension -> extension.getUrl().equals(DISPLAY_EXTENSION_URL))
Addressed

2021-09-28 09:59 UTC, bbell-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/utils/CodeableConceptMappingUtils.java
> +            .filter(extension -> extension.getUrl().equals(DESCRIPTION_DISPLAY_URL))
Addressed

2021-09-28 10:03 UTC, rorysproule1 approved these changes

2021-09-28 17:41 UTC, bartek-sarul approved these changes

2021-09-29 07:16 UTC, merged