(Testing fixes) NIAD-1699: Observation: NIAD-1476 has resulted in spurious 'Interpretation' label being generated in most Observation output
nhsconnect/integration-adaptor-gp2gp pull request #353
Opened 2021-09-27 09:22 UTC by bbell-kainos

2021-09-27 14:31 UTC, rorysproule1 approved these changes

2021-09-28 09:00 UTC, bartek-sarul requested changes

2021-09-28 14:41 UTC, bbell-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ObservationStatementMapper.java
> +        interpretationCodeMapped = false;
Addressed

2021-09-28 14:41 UTC, bbell-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/ObservationMapper.java
> +        interpretationCodeMapped = false;
Addressed

2021-09-29 08:58 UTC, bartek-sarul approved these changes

2021-09-29 12:06 UTC, merged