NIAD-1390: Created database documentation
nhsconnect/integration-adaptor-gp2gp pull request #355
Opened 2021-09-27 13:23 UTC by ElliotB-96

2021-09-28 09:00 UTC, bartek-sarul requested changes

2021-09-28 09:00 UTC, bartek-sarul commented on documentation/database/database.md
> +# Database Objects
Add [here](https://github.com/nhsconnect/integration-adaptor-gp2gp/blob/main/OPERATING.md#database-design) a link to your file

2021-09-28 17:41 UTC, bartek-sarul approved these changes

2021-10-04 09:21 UTC, bbell-kainos approved these changes

2021-10-04 09:43 UTC, merged