ReferralRequest: Annotation handling - suppress @ when no author/time
nhsconnect/integration-adaptor-gp2gp pull request #371
Opened 2021-10-05 14:17 UTC by AlanSimpson1723

2021-10-05 15:07 UTC, rorysproule1 submitted a review, later dismissed

2021-10-06 11:47 UTC, pawel-wlodarczyk-kainos requested changes

2021-10-06 11:47 UTC, pawel-wlodarczyk-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/RequestStatementMapper.java
> +            if (author.equals(StringUtils.EMPTY) && time.equals(StringUtils.EMPTY)) {
There is no need to compare those strings this way. You could write it this way (my recommendation):
```java
return author.isEmpty() && time.isEmpty()
	? String.format(NOTE_WITH_NO_AUTHOR_AND_TIME, value.getText())
	: String.format(NOTE, author, time, value.getText());
```
or with `if`s:
```java
if (author.isEmpty() && time.isEmpty()) {
	return String.format(NOTE_WITH_NO_AUTHOR_AND_TIME, value.getText());
} else {
	return String.format(NOTE, author, time, value.getText());
}
```

2021-10-06 12:17 UTC, pawel-wlodarczyk-kainos approved these changes

2021-10-06 12:57 UTC, merged