Niad 1547 diagnostic report report level comments to appear before specimen compound statement
nhsconnect/integration-adaptor-gp2gp pull request #385
Opened 2021-10-13 08:51 UTC by pawel-wlodarczyk-kainos

The idea is to unwrap `<NarrativeStatement>`  from `<component>` tag and uplift it to the same level as `<CompoundStatement>`.

2021-10-13 09:48 UTC, ElliotB-96 commented
@pawel-wlodarczyk-kainos , Can you recreate this PR to merge into https://github.com/nhsconnect/integration-adaptor-gp2gp/pull/359 as that is where we are collecting the changes to diagnostic report

2021-10-13 10:14 UTC, bartek-sarul requested changes

2021-10-13 10:14 UTC, bartek-sarul commented on service/src/test/resources/ehr/mapper/diagnosticreport/diagnostic-report-with-coded-diagnosis.xml
> +</NarrativeStatement>
I think indentation is wrong here

2021-10-18 16:41 UTC, bchotkowski commented
Already refactored and merged into NIAD-1780, 
Closing this PR, pointing to a wrong branch (main instead of #359)

2021-10-18 16:41 UTC, closed without merging