NIAD-1720: MedicationRequest: GPC Spec change (unpublished) - requester override recorder as attribution
nhsconnect/integration-adaptor-gp2gp pull request #393
Opened 2021-10-15 14:59 UTC by bbell-kainos

2021-10-19 07:49 UTC, ElliotB-96 commented on service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapperTest.java
> -            Arguments.of(INPUT_JSON_ON_BEHALF_OF_ORG_WITH_MULTIPLE_TYPES, OUTPUT_XML_WITH_AUTHORISE_ORG_INFO_MULTIPLE_TYPES),
Are there no additional tests to be added for this change?

2021-10-19 11:18 UTC, bartek-sarul requested changes

2021-10-19 11:18 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
> +            final var agent = requester.getAgent();
You check for `if (medicationRequest.hasRequester()) {` but not for `requester.hasAgent()` ?

2021-10-19 11:18 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
> +                && requester.hasOnBehalfOf()) {
Might be more readable if you would add more indentation on this line

2021-10-20 11:24 UTC, bartek-sarul requested changes

2021-10-20 11:24 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/MedicationStatementMapper.java
> +                && requester.hasOnBehalfOf()) {
What I meant here is:
```
if (ResourceType.Practitioner.name().equals(agent.getReferenceElement().getResourceType())
        && requester.hasOnBehalfOf()) {
    var onBehalfOf = requester.getOnBehalfOf();
    ...
```

2021-10-21 08:00 UTC, merged