NIAD-1802: Date extraction from observations
nhsconnect/integration-adaptor-gp2gp pull request #401
Opened 2021-10-20 11:36 UTC by ElliotB-96

-  Added date extraction from observations

2021-10-20 12:10 UTC, rorysproule1 approved these changes

2021-10-21 12:53 UTC, bartek-sarul requested changes

2021-10-21 12:53 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapper.java
> +    private void buildNarrativeStatementForObservationTimes(List<Observation> observations, StringBuilder reportLevelNarrativeStatements,
It's better to have all on the same line
```
private void buildNarrativeStatementForObservationTimes(
    List<Observation> observations, StringBuilder reportLevelNarrativeStatements, InstantType diagnosticReportIssued) {
```
or each on a separate:
```
private void buildNarrativeStatementForObservationTimes(
        List<Observation> observations, 
        StringBuilder reportLevelNarrativeStatements,
        InstantType diagnosticReportIssued) {
    ...
```
Notice the 8 spaces indent in the second example - to better distinguish arguments from function body

2021-10-21 12:53 UTC, bartek-sarul commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/diagnosticreport/DiagnosticReportMapper.java
> +        }
Can be:
```suggestion
        observations.stream()
            .filter(observation -> observation.hasEffectiveDateTimeType() || observation.hasEffectivePeriod())
            .findFirst()
            .map(this::extractDateFromObservation)
            .map(dateString -> buildNarrativeStatementForDiagnosticReport(
                diagnosticReportIssued, CommentType.AGGREGATE_COMMENT_SET.getCode(), dateString))
            .ifPresent(reportLevelNarrativeStatements::append);
```

2021-11-02 06:47 UTC, dawidskainos approved these changes

2021-11-02 08:11 UTC, bbell-kainos approved these changes

2021-11-02 08:12 UTC, merged