NIAD-1579: Condition: Immunizations and Medications can't be displayed as problems in SystmOne
nhsconnect/integration-adaptor-gp2gp pull request #424
Opened 2021-11-04 17:18 UTC by rorysproule1

2021-11-11 11:24 UTC, bbell-kainos requested changes

2021-11-11 11:24 UTC, bbell-kainos commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/wrapper/ConditionWrapper.java
> +
Remove this line

2021-11-11 13:18 UTC, bbell-kainos submitted a review, later dismissed

2021-11-12 09:30 UTC, bchotkowski commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/ConditionLinkSetMapper.java
> +            .map(value -> (Reference) value)
```suggestion
            .map(Reference.class::cast)
```
 might look tidier

2021-11-12 09:31 UTC, bchotkowski submitted a review, later dismissed

2021-11-12 09:39 UTC, bchotkowski approved these changes

2021-11-12 10:02 UTC, bbell-kainos approved these changes

2021-11-12 10:03 UTC, merged