Translating FHIR Narrative (Comment Note) Observation to Narrative Statement
nhsconnect/integration-adaptor-gp2gp pull request #66
Opened 2021-02-04 15:12 UTC by z-uddin

- Created a NarrativeStatement mapper, which consumes FHIR Observation object and uses this to fill a Narrative Statement XML template.
- Unit tests parse a JSON file to a FHIR Observation object and then compares output from running map method to expected XML

2021-02-04 15:41 UTC, Broom94 commented on service/src/test/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NarrativeStatementMapperTest.java
> +    private static final String OUTPUT_XML_3 = "/ehr/mapper/observation/expected-output-narrative-statement-3.xml";
Maybe name these more descriptively?

2021-02-04 15:42 UTC, Broom94 commented on service/src/main/java/uk/nhs/adaptors/gp2gp/ehr/mapper/NarrativeStatementMapper.java
> +                    .atZone(ZoneId.of("Europe/London"))
use a variable for Europe/london

2021-02-04 16:44 UTC, Broom94 submitted a review, later dismissed

2021-02-04 16:59 UTC, mattd-kainos commented on service/src/main/resources/templates/ehr_narrative_statement_template.mustache
> +    <text>{{{comment}}}</text>
I think we need to use double braces {{}} here so that special characters are escaped

2021-02-04 17:07 UTC, mattd-kainos requested changes
need to ensure special characters in comment are escaped in XML

2021-02-05 13:02 UTC, mattd-kainos commented on service/src/main/resources/templates/ehr_narrative_statement_template.mustache
> +<NarrativeStatement classCode="OBS" moodCode="EVN">
NarrativeStatement needs to be within a component with contextConductionInd included conditional on isNested flag. See row 10 of mappings spec.

2021-02-05 15:18 UTC, mattd-kainos commented on service/src/main/resources/templates/ehr_narrative_statement_template.mustache
> +    <NarrativeStatement classCode="OBS" moodCode="EVN">
This way of doing it is correct, but there is a more compact way to write it.

`<component typeCode="COMP"{{#isNested}} contextConductionInd="true"{{/isNested}}>`

2021-02-05 15:19 UTC, mattd-kainos approved these changes

2021-02-05 15:25 UTC, Broom94 approved these changes
Good job!

2021-02-05 15:37 UTC, mattd-kainos approved these changes

2021-02-05 15:38 UTC, merged