Implemented mongo db connection and repository
nhsconnect/integration-adaptor-gp2gp pull request #8
Opened 2020-12-03 09:05 UTC by mmackiewicz1

2020-12-03 10:17 UTC, Broom94 commented on service/build.gradle
> +
Do we need whitespace here

2020-12-03 10:19 UTC, mmackiewicz1 commented on service/build.gradle
> +
I will remove it.

2020-12-03 10:22 UTC, Broom94 requested changes
Good job on this one, those log message are really clear and easy to understand! Should we have a test container setup for the db?

2020-12-03 10:22 UTC, Broom94 commented on service/src/main/resources/application.yml
> +  cosmosDbEnabled: ${GP2GP_COSMOS_DB_ENABLED:false}
Please add environment variables to ./README.md +  update ./docker/docker-compose.yml with these new variables

2020-12-03 10:52 UTC, Broom94 requested changes

2020-12-03 10:52 UTC, Broom94 commented on README.md
Please add necessary variables added in the environment variable list to the section below 'How to run service'

2020-12-03 10:52 UTC, Broom94 commented on service/src/main/java/uk/nhs/adaptors/gp2gp/TestClass.java
> +}
Remove?

2020-12-03 10:54 UTC, mmackiewicz1 commented on service/src/main/java/uk/nhs/adaptors/gp2gp/TestClass.java
> +}
Sorry, commited it by accident.

2020-12-03 15:48 UTC, mattd-kainos approved these changes

2020-12-04 13:14 UTC, Broom94 approved these changes

2020-12-04 13:27 UTC, merged